on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-CNA-500-BDX-5-1-cryptography-anthony.ardhuin.git

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: epitechcontent/epitest-docker:latest
        steps:

            - uses: actions/checkout@v4

            - name: Build project
              run: make

            - name: Check binaries
              run: |
                if [ -f ./my_pgp ]; then
                    echo "::notice::PGP binary OK"
                else
                    echo "::error file=./my_pgp::PGP binary does not exist"
                    exit 1
                fi

    mirror:
      name: Push to Mirror
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Push to mirror
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: ${{ env.MIRROR_URL }}
            ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}